# frozen_string_literal: true
name              'chrony'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures chrony, an application used to maintain the accuracy of the system clock (similar to NTPd).'
version           '1.2.7'
issues_url        'https://github.com/sous-chefs/chrony/issues'
source_url        'https://github.com/sous-chefs/chrony'
chef_version      '>= 15.3'

supports 'debian', '>= 11.0'
supports 'ubuntu', '>= 20.04'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'almalinux', '>= 8.0'
supports 'amazon'
