# frozen_string_literal: true
name              'chrony'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures chrony, an application used to maintain the accuracy of the system clock (similar to NTPd).'
version           '1.2.7'
issues_url        'https://github.com/sous-chefs/chrony/issues'
source_url        'https://github.com/sous-chefs/chrony'
chef_version      '>= 15.3'

supports 'debian', '>= 12.0'
supports 'ubuntu', '>= 22.04'
supports 'redhat', '>= 9.0'
supports 'rocky', '>= 9.0'
supports 'almalinux', '>= 9.0'
supports 'amazon'
